### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by Hypoaristerolactotherapist** [gherkins/regexpbuilderphp#20]
Hi,

when you ship this (great, by the way) project to Packagist, could you remove the .git directory. It messes up my git installation by making your code as a submodule of my code that I have many pains to push.

Each time I update I need to manually remove your .git directory, add all your files to my change list and then I can commit.

Thanks

**Comment by gherkins** [comment]
Hi,

thanks, but isn't that the expected behaviour when installing via composer?
Packagist just fetches the code from github, doesn't it?

There might a workaround to prevent the .git folder from being created:
http://stackoverflow.com/questions/25981292/how-to-make-composer-not-create-a-git-directory-for-a-package

**Comment by Hypoaristerolactotherapist** [comment]
I'll try that, thanks.
On all packages, only 4 projects downloaded their .git directory and where considered as submodules. I need to commit all of it as one to deploy from the central repository.

**Comment by gherkins** [comment]
That might be related to whether you install tagged releases or dev versions of a package:

https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
